# Generated by Django 5.1.2 on 2024-11-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='checkin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='posicao_fila',
            field=models.IntegerField(null=True),
        ),
    ]
