# Generated by Django 5.1.2 on 2024-11-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0004_agendamento_checkin_agendamento_posicao_fila'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
