# Generated by Django 5.1.2 on 2024-10-29 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cardapio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('CAFE', 'Café da manhã'), ('ALMOCO', 'Almoço'), ('JANTA', 'Janta')], max_length=100)),
                ('horario_abertura', models.TimeField()),
                ('horario_fechamento', models.TimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('RU', 'Restaurante Universitário'), ('RU2', 'Restaurante Universitário 2')], max_length=100)),
                ('campus', models.CharField(choices=[('SM', 'Campus Santa Maria'), ('FW', 'Campus Frederico Westphalen'), ('PA', 'Campus Palmeira das Missões'), ('CS', 'Campus Cachoeira do Sul')], max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('refeicoes_oferecidas', models.ManyToManyField(to='restaurante.refeicao')),
            ],
        ),
        migrations.CreateModel(
            name='CardapioRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_oferecida', models.DateField()),
                ('cardapio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardapio.cardapio')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante.restaurante')),
            ],
        ),
    ]
