# Generated by Django 5.1.2 on 2024-11-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refeicao',
            name='limite_agendamentos',
            field=models.IntegerField(default=100),
        ),
    ]
