# Generated by Django 5.1.2 on 2024-10-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.TextField()),
                ('acompanhamento', models.TextField()),
                ('bebidas', models.TextField()),
            ],
        ),
    ]
