# Generated by Django 5.1.2 on 2024-10-29 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cardapio', '0001_initial'),
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardapio',
            name='refeicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante.refeicao'),
        ),
    ]
